name: Linux JS Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]

jobs:
  linuxjs:
    name: JS
    strategy:
      matrix:
        group:
          [
            js-debugger,
          ]
      fail-fast: false
    runs-on: ubuntu-20.04
    timeout-minutes: 40
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Install dependencies
        env:
          GROUP: ${{ matrix.group }}
        run: |
          bash ./scripts/ci_install.sh

      - name: Create logs dir
        run: mkdir -p logs

      - name: Where am I?
        run: pwd

      - name: Run test ${{ matrix.group }}
        env:
          GROUP: ${{ matrix.group }}
        run: |
          bash ./scripts/ci_script.sh

      - name: What's in there?
        run: ls

      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: logs/
